# agents/document_agent.py - LLM-powered document analyzer + PPTX generator
import os, time, uuid, re, json
from tools import extract_text_from_pdf
from memory import SessionStore
import openai
from pptx import Presentation

MODEL = os.environ.get("UTO_LLM_MODEL", "gpt-4o-mini")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
if OPENAI_API_KEY:
    openai.api_key = OPENAI_API_KEY

def call_chat(messages, max_tokens=1024, temperature=0.2):
    if not OPENAI_API_KEY:
        return {"text": "OPENAI_API_KEY not set — placeholder response."}
    resp = openai.ChatCompletion.create(model=MODEL, messages=messages, max_tokens=max_tokens, temperature=temperature)
    return {"text": resp["choices"][0]["message"]["content"], "raw": resp}

def build_pptx(summary, action_items, highlights, out_path):
    prs = Presentation()
    s = prs.slides.add_slide(prs.slide_layouts[0])
    title = s.shapes.title
    subtitle = s.placeholders[1]
    title.text = "Document Summary"
    subtitle.text = f"Generated by UTO — {time.strftime('%Y-%m-%d %H:%M')}"
    s2 = prs.slides.add_slide(prs.slide_layouts[1])
    s2.shapes.title.text = "Executive Summary"
    body = s2.shapes.placeholders[1].text_frame
    body.clear()
    body.text = summary[:2000]
    s3 = prs.slides.add_slide(prs.slide_layouts[1])
    s3.shapes.title.text = "Highlights"
    tf = s3.shapes.placeholders[1].text_frame
    for h in highlights[:8]:
        p = tf.add_paragraph(); p.text = f"• {h}"; p.level = 0
    s4 = prs.slides.add_slide(prs.slide_layouts[1])
    s4.shapes.title.text = "Action Items"
    tf2 = s4.shapes.placeholders[1].text_frame
    for a in action_items[:10]:
        p = tf2.add_paragraph(); p.text = f"• {a}"; p.level = 0
    prs.save(out_path)
    return out_path

class DocumentAgent:
    def __init__(self, name="document_agent", bus=None, session_store: SessionStore=None):
        self.name = name
        self.bus = bus
        self.session_store = session_store or SessionStore()

    def analyze(self, session_id, file_path, options=None):
        options = options or {}
        text = extract_text_from_pdf(file_path)
        if isinstance(text, str) and text.startswith("PDF extraction error"):
            out = {"error": text}
            self.session_store.push_message(session_id, "document_agent", str(out))
            return out

        prompt_text = text[:30000]
        system = {"role": "system", "content": "You are an expert document analyst. Produce an executive summary, 5-10 action items, key highlights, and 3 short quotes with citations (if available). Output in JSON with keys: summary, action_items, highlights, quotes."}
        user = {"role": "user", "content": f"Analyze the following document text and output JSON.\n\nDocument:\n{prompt_text}"}

        llm_resp = call_chat([system, user], max_tokens=1500)
        llm_text = llm_resp.get("text", "")

        json_candidate = None
        try:
            m = re.search(r"\{.*\}", llm_text, re.S)
            if m:
                json_candidate = json.loads(m.group(0))
            else:
                json_candidate = {"summary": llm_text, "action_items": [], "highlights": [], "quotes": []}
        except Exception:
            json_candidate = {"summary": llm_text, "action_items": [], "highlights": [], "quotes": []}

        out_dir = "outputs"; os.makedirs(out_dir, exist_ok=True)
        pptx_name = f"{session_id}_doc_{uuid.uuid4().hex[:8]}.pptx"
        pptx_path = os.path.join(out_dir, pptx_name)
        try:
            build_pptx(summary=json_candidate.get("summary","")[:3000], action_items=json_candidate.get("action_items",[]), highlights=json_candidate.get("highlights",[]), out_path=pptx_path)
        except Exception as e:
            pptx_path = None

        out = {"summary": json_candidate.get("summary"), "action_items": json_candidate.get("action_items"), "highlights": json_candidate.get("highlights"), "quotes": json_candidate.get("quotes"), "pptx": pptx_path, "llm_raw": llm_resp.get("raw") if isinstance(llm_resp, dict) else None}
        self.session_store.push_message(session_id, "document_agent", str({"document_analysis": out}))
        return out
